version: "3.9"

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env

  server:
    build: ./server
    ports:
      - "5000:80"
    env_file:
      - ./server/.env
      - ./pg/.env

  database:
    image: postgres:16.0-alpine
    env_file:
      - ./pg/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./pg/sql/init:/docker-entrypoint-initdb.d
    restart: always

volumes:
  pg_data:
    driver: local
