version: "3.8"

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      DB_NAME: animate
      DB_USERNAME: postgres
    env_file:
      - ./client/.env

  server:
    build: ./server
    ports:
      - "5000:80"
    env_file:
      - ./server/.env

  database:
    image: postgres:16.0-alpine
    ports:
      - "5440:5432"
    env_file:
      - ./pg/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./pg/sql/init:/docker-entrypoint-initdb.d
    restart: always

volumes:
  pg_data:
    driver: local
