import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";

const baseFont = Quicksand({
  weight: ["400", "500", "600"],
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`fg ${baseFont.className}`}>{children}</body>
    </html>
  );
}
