import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const baseFont = Inter({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`flex flex-col min-h-screen fg ${baseFont.className}`}>
        {children}
      </body>
    </html>
  );
}
